version: '3.7'

services:

  slick:
    container_name: slick
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/app/client'
      - '/app/client/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
  
  slick-server:
    container_name: slick-server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - './server:/app/server'
    ports:
      - 5000:5000